"""add recipe columns and column constraints

Revision ID: f2db2bd6796c
Revises: e2f71ce3909a
Create Date: 2024-12-04 14:25:15.536820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2db2bd6796c'
down_revision = 'e2f71ce3909a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('instructions', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('minutes_to_complete', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('minutes_to_complete')
        batch_op.drop_column('instructions')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
